name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Roda todos os dias à meia-noite
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: rdgr1  # Substitua pelo seu username
          outputs: |
            github-contribution-grid-snake.svg

      - name: Commit e push do resultado
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
